name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest
      - run: clj -M:test -m kaocha.runner :api :infra

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest
      - run: clj -M:test -m kaocha.runner :integration

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - run: clj -M:test -m kaocha.runner :ui
        env:
          CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
          HEADLESS: "true"
